### ISSUE TITLE
Packetization

### ISSUE THREAD

**Issue by aboba** [WICG/web-codecs#1]
The APIs make sense for encoding a bitstream, transporting it reliably then decoding and rendering it. 

But what if you want to packetize an encoded bitstream within QUIC datagrams and then reassemble and decode it on the other side? 

Or what if you want a mixture of reliable and unreliable transport?  For example, you might want to provide different transport for keyframes and P-frames.  So you might want to separate out portions of the encoded bitstream for reliable transport, and other portions for datagram transport.

**Comment by pthatcherg** [comment]
I think this overlaps, to a degree, with this new tracking issue: https://github.com/WICG/web-codecs/issues/24.  If you squint, RTP is a container format.
