### ISSUE TITLE
VideoDecoder decoding Failed. but error

### ISSUE THREAD

**Issue by dhkimest** [WICG/web-codecs#100]
I just try to changed the code from video/mp4 to VideoDecoder/encodedChunk.

But, I don't get any decoded Frame.
and, Haven't any error codes. error callback passing null.
Below I attached my console log. and parts of codes
What can i try next?

![Screenshot from 2020-10-27 06-55-45](https://user-images.githubusercontent.com/6565840/97233001-92c05e00-1821-11eb-8d11-eced6f6ce08e.png)

function paintFrameToCanvas(videoFrame) {
  // Paint every video frame ASAP for lowest latency.
  // canvasContext.transferFromImageBitmap(videoFrame.transferToImageBitmap());
  console.log("paintFrameToCanvas ", videoFrame);
...
}
...
if(!videoDecoder) {
  if(!initialTimestamp) {
    initialTimestamp = videoInfo.rtpTimeStamp;
  }

  var
  sps = [videoInfo.spsPayload] || [],
  pps = [videoInfo.ppsPayload] || [],
  sequenceParameterSets = [],
  pictureParameterSets = [],
  i;

  for (i = 0; i < sps.length; i++) {
    sequenceParameterSets.push((sps[i].byteLength & 0xFF00) >>> 8);
    sequenceParameterSets.push((sps[i].byteLength & 0xFF)); // sequenceParameterSetLength
    sequenceParameterSets = sequenceParameterSets.concat(Array.prototype.slice.call(sps[i])); // SPS
  }        
  // assemble the PPSs
  for (i = 0; i < pps.length; i++) {
    pictureParameterSets.push((pps[i].byteLength & 0xFF00) >>> 8);
    pictureParameterSets.push((pps[i].byteLength & 0xFF));
    pictureParameterSets = pictureParameterSets.concat(Array.prototype.slice.call(pps[i]));
  }

  var avcC = box(types.avcC, new Uint8Array([
    0x01, // configurationVersion
    videoInfo.profileIdc, // AVCProfileIndication
    videoInfo.profileCompatibility ? videoInfo.profileCompatibility : 0, // profile_compatibility
    videoInfo.levelIdc, // AVCLevelIndication
    0xff // lengthSizeMinusOne, hard-coded to 4 bytes
  ].concat([
    sps.length // numOfSequenceParameterSets
  ]).concat(sequenceParameterSets).concat([
    pps.length // numOfPictureParameterSets
  ]).concat(pictureParameterSets))).slice(8);

  videoDecoder = new VideoDecoder({
    output: paintFrameToCanvas,
    error: (e) => {
      console.log(e.message);
    }
  });

  videoDecoder.configure({
    codec : videoInfo.codecInfo,
    description : avcC,
    codecWidth: videoInfo.width,
    codecHeight: videoInfo.height,
  })

  console.log(videoDecoder);
}

var encodedVideoChunk = new EncodedVideoChunk({
  type : videoInfo.frameType === 'I' ? 'key' : 'delta',
  timestamp : videoInfo.rtpTimeStamp - initialTimestamp,
  data : new Uint8Array(streamData.frameData),
});

console.log(videoDecoder);

videoDecoder.decode(encodedVideoChunk);

**Comment by tguilbert-google** [comment]
This isn't really a direct answer to your question, but there is [a CL](https://chromium-review.googlesource.com/c/chromium/src/+/2499422) that should make it into Canary soon (1-2 days?), which fixes the lack of exception on error. We should have a better idea of what is going wrong then.

**Comment by dhkimest** [comment]
Thanks, than I'll be waiting for next Canary.

**Comment by dhkimest** [comment]
If I get some examples of using VideoDecoder for avc(h.264).
then, It's much easier.
Where can I find any examples for H.264 about use VideoDecoder?

**Comment by dhkimest** [comment]
My canary  just updated.
So, I checked one more try.

error log wrote under, but you know
=> 'Decoding error: Null or empty decoder buffer.'

How can I solve this issue?
Are there any initialize for decoder buffer? 
Or, decoder buffer is different from decodeQueue?

**Comment by tguilbert-google** [comment]
Can you confirm that `data : new Uint8Array(streamData.frameData),` actually has valid data?

**Comment by dhkimest** [comment]
OK, I add more log for streamData.frameData please, check this out!

VideoDecoder {decodeQueueSize: 0, state: "configured"}
canvasTagPlayer.js:529 streamData.frameData Uint8Array(102182) [0, 0, 0, 1, 103, 100, 0, 31, 172, 27, 26, 128, 80, 5, 191, 240, 22, 224, 32, 32, 40, 0, 0, 31, 64, 0, 7, 83, 7, 67, 0, 23, 254, 0, 1, 171, 63, 93, 229, 198, 134, 0, 47, 252, 0, 3, 86, 126, 187, 203, 133, 0, 0, 0, 1, 104, 238, 56, 48, 0, 0, 0, 1, 101, 184, 0, 2, 0, 0, 3, 2, 255, 249, 45, 239, 67, 222, 120, 9, 115, 2, 219, 29, 151, 146, 204, 72, 163, 206, 247, 82, 232, 243, 197, 93, 234, 121, 72, 57, 74, …]
canvasTagPlayer.js:537 VideoDecoder {decodeQueueSize: 0, state: "configured"} EncodedVideoChunk {type: "key", timestamp: 0, duration: null, data: ArrayBuffer(102182)}
canvasTagPlayer.js:529 streamData.frameData Uint8Array(3669) [0, 0, 0, 1, 97, 224, 0, 32, 0, 69, 112, 143, 248, 233, 169, 186, 219, 162, 204, 126, 234, 23, 93, 172, 125, 171, 24, 77, 126, 98, 108, 121, 136, 231, 64, 73, 192, 44, 95, 184, 209, 84, 52, 227, 65, 54, 116, 147, 66, 163, 250, 220, 205, 129, 124, 248, 235, 241, 43, 156, 40, 239, 242, 162, 52, 239, 151, 131, 4, 17, 155, 137, 145, 14, 20, 130, 203, 36, 222, 220, 115, 228, 83, 151, 167, 12, 201, 6, 167, 247, 224, 197, 169, 228, 112, 98, 112, 200, 248, 248, …]
canvasTagPlayer.js:537 VideoDecoder {decodeQueueSize: 1, state: "configured"} EncodedVideoChunk {type: "delta", timestamp: 0, duration: null, data: ArrayBuffer(3669)}
canvasTagPlayer.js:529 streamData.frameData Uint8Array(5789) [0, 0, 0, 1, 97, 224, 0, 64, 0, 133, 112, 143, 249, 52, 167, 180, 219, 17, 47, 237, 38, 137, 237, 107, 204, 205, 84, 115, 24, 246, 229, 141, 186, 27, 119, 196, 58, 106, 19, 216, 220, 253, 87, 191, 198, 8, 1, 136, 19, 218, 244, 75, 8, 196, 116, 254, 156, 48, 112, 136, 233, 27, 71, 129, 107, 170, 203, 151, 64, 190, 229, 41, 9, 199, 66, 74, 95, 53, 133, 149, 75, 121, 238, 25, 19, 30, 254, 129, 64, 5, 1, 238, 120, 137, 111, 252, 102, 79, 87, 31, …]
canvasTagPlayer.js:537 VideoDecoder {decodeQueueSize: 2, state: "configured"} EncodedVideoChunk {type: "delta", timestamp: 0, duration: null, data: ArrayBuffer(5789)}
canvasTagPlayer.js:529 streamData.frameData Uint8Array(6483) [0, 0, 0, 1, 97, 224, 0, 96, 0, 197, 112, 143, 248, 237, 231, 103, 69, 177, 45, 15, 54, 192, 78, 133, 208, 83, 157, 40, 118, 138, 173, 36, 178, 105, 32, 39, 222, 132, 228, 90, 31, 101, 27, 175, 250, 218, 237, 218, 167, 144, 76, 138, 32, 115, 156, 142, 44, 250, 3, 173, 220, 225, 117, 168, 92, 169, 131, 66, 113, 77, 227, 41, 244, 90, 249, 133, 92, 239, 254, 14, 116, 252, 117, 175, 83, 192, 84, 238, 177, 245, 254, 158, 104, 21, 121, 68, 155, 199, 170, 226, …]
canvasTagPlayer.js:537 VideoDecoder {decodeQueueSize: 3, state: "configured"} EncodedVideoChunk {type: "delta", timestamp: 0, duration: null, data: ArrayBuffer(6483)}
canvasTagPlayer.js:529 streamData.frameData Uint8Array(6677) [0, 0, 0, 1, 97, 224, 0, 128, 1, 5, 112, 143, 243, 17, 28, 161, 253, 50, 167, 203, 217, 150, 184, 2, 197, 235, 219, 108, 220, 179, 155, 44, 108, 202, 122, 139, 73, 5, 141, 78, 85, 126, 58, 231, 37, 0, 69, 63, 59, 96, 134, 136, 132, 34, 203, 210, 167, 187, 75, 21, 168, 176, 20, 117, 131, 15, 233, 17, 63, 52, 8, 157, 55, 174, 172, 24, 224, 187, 191, 79, 203, 121, 2, 170, 77, 155, 167, 179, 78, 2, 222, 217, 0, 239, 97, 209, 92, 155, 133, 132, …]
canvasTagPlayer.js:537 VideoDecoder {decodeQueueSize: 4, state: "configured"} EncodedVideoChunk {type: "delta", timestamp: 0, duration: null, data: ArrayBuffer(6677)}
canvasTagPlayer.js:529 streamData.frameData Uint8Array(6873) [0, 0, 0, 1, 97, 224, 0, 160, 1, 69, 112, 143, 232, 109, 137, 169, 191, 29, 210, 147, 213, 108, 244, 175, 173, 8, 76, 49, 218, 185, 138, 188, 122, 189, 83, 138, 41, 212, 80, 143, 79, 4, 79, 224, 17, 23, 154, 247, 161, 76, 10, 149, 151, 29, 208, 163, 240, 47, 147, 200, 0, 71, 12, 244, 109, 4, 41, 18, 228, 99, 160, 205, 137, 45, 196, 187, 12, 171, 134, 30, 148, 1, 31, 228, 159, 167, 39, 36, 241, 54, 251, 137, 226, 138, 175, 97, 160, 87, 144, 27, …]
canvasTagPlayer.js:537 VideoDecoder {decodeQueueSize: 5, state: "configured"} EncodedVideoChunk {type: "delta", timestamp: 0, duration: null, data: ArrayBuffer(6873)}
canvasTagPlayer.js:529 streamData.frameData Uint8Array(6928) [0, 0, 0, 1, 97, 224, 0, 192, 1, 133, 112, 143, 243, 9, 243, 129, 254, 128, 187, 221, 46, 63, 228, 5, 66, 39, 59, 56, 165, 77, 137, 47, 199, 80, 125, 171, 107, 123, 196, 150, 111, 175, 254, 79, 34, 85, 241, 35, 51, 217, 251, 9, 20, 157, 186, 246, 180, 63, 110, 98, 152, 193, 141, 184, 187, 153, 212, 146, 99, 45, 16, 226, 146, 72, 253, 133, 221, 103, 179, 64, 212, 0, 45, 171, 98, 239, 107, 110, 20, 93, 133, 240, 180, 125, 73, 95, 184, 168, 246, 22, …]
canvasTagPlayer.js:537 VideoDecoder {decodeQueueSize: 6, state: "configured"} EncodedVideoChunk {type: "delta", timestamp: 0, duration: null, data: ArrayBuffer(6928)}
canvasTagPlayer.js:529 streamData.frameData Uint8Array(7009) [0, 0, 0, 1, 97, 224, 0, 224, 1, 197, 112, 143, 114, 148, 77, 241, 220, 181, 196, 52, 21, 190, 131, 85, 119, 168, 101, 28, 143, 175, 126, 35, 190, 101, 121, 18, 26, 217, 5, 173, 182, 223, 251, 91, 242, 66, 166, 243, 167, 112, 80, 174, 110, 174, 157, 128, 227, 74, 2, 207, 217, 34, 162, 67, 33, 211, 97, 94, 13, 135, 163, 12, 122, 246, 113, 197, 57, 17, 210, 172, 238, 213, 176, 50, 193, 2, 213, 187, 177, 143, 71, 24, 121, 120, 211, 165, 39, 233, 80, 147, …]
canvasTagPlayer.js:537 VideoDecoder {decodeQueueSize: 7, state: "configured"} EncodedVideoChunk {type: "delta", timestamp: 0, duration: null, data: ArrayBuffer(7009)}
canvasTagPlayer.js:513 Decoding error: Null or empty decoder buffer.
canvasTagPlayer.js:529 streamData.frameData Uint8Array(6899) [0, 0, 0, 1, 97, 224, 1, 0, 2, 5, 112, 143, 232, 109, 137, 166, 254, 248, 215, 220, 18, 74, 23, 51, 105, 247, 136, 248, 80, 166, 55, 177, 187, 48, 196, 216, 64, 255, 122, 98, 107, 237, 129, 209, 131, 120, 240, 147, 73, 20, 49, 210, 147, 247, 191, 224, 135, 255, 85, 46, 26, 220, 137, 26, 69, 230, 238, 38, 178, 163, 6, 224, 127, 156, 29, 44, 241, 157, 4, 141, 184, 226, 26, 69, 57, 26, 0, 187, 115, 116, 190, 198, 11, 9, 221, 176, 98, 42, 94, 52, …]
canvasTagPlayer.js:537 VideoDecoder {decodeQueueSize: 0, state: "closed"} EncodedVideoChunk {type: "delta", timestamp: 0, duration: null, data: ArrayBuffer(6899)}

Thanks!

**Comment by tguilbert-google** [comment]
Ok, TY. There is something that is going wrong with the decoder_buffer creation in the [H264 converter](https://source.chromium.org/chromium/chromium/src/+/master:media/filters/h264_to_annex_b_bitstream_converter.cc;l=72). I personally don't know enough about that code (and H264 in general) to say if it's a bug with chromium, or with your code.

Could you open a bug at crbug.com and attach your webpage and video file? This will be easier to debug if we run your code.

**Comment by dhkimest** [comment]
I think, It's not easy what you run the code
It's rtp/rtsp player, so, I have no idea how I serve the code run for you.

If my guess is correct, avcc parsing seems to be causing the problem.
So, If I know the form of avcC suitable for the configuration, I think this problem will be solved.

In my code, avcC is mp4 avcC box.
Is it correct?

If I can't handle this while in to day, than I open a bug at crbug.com.

**Comment by tguilbert-google** [comment]
You are right that it might be avcC parsing. However, I would expect a "Failed to parse avcC." message if it didn't work out. If you don't get that message, but you do when you enter gibberish for the avcC, it's probably failing in [CalculateNeededOutputBufferSize](https://source.chromium.org/chromium/chromium/src/+/master:media/filters/h264_to_annex_b_bitstream_converter.cc;l=72) or [ConvertNalUnitStreamToByteStream](https://source.chromium.org/chromium/chromium/src/+/master:media/filters/h264_to_annex_b_bitstream_converter.cc;l=157)

We will definitively improve the error reporting for those failures. In the meantime, while the code linked above is dense, it might help your debugging to see the what is being done with the bytes you give it?

**Comment by dhkimest** [comment]
This log is typedarray about avcC Please check this out.
Uint8Array(62) [1, 100, 0, 31, 255, 1, 0, 47, 103, 100, 0, 31, 172, 27, 26, 128, 80, 5, 191, 240, 22, 224, 32, 32, 40, 0, 0, 31, 64, 0, 7, 83, 7, 67, 0, 23, 254, 0, 1, 171, 63, 93, 229, 198, 134, 0, 47, 252, 0, 3, 86, 126, 187, 203, 133, 1, 0, 4, 104, 238, 56, 48]

this capture is in mp4 reader
![image](https://user-images.githubusercontent.com/6565840/97649388-8e52aa00-1a9a-11eb-8ae4-606782371350.png)

Thanks,

**Comment by tguilbert-google** [comment]
I wrote a demo:
https://tguilbert-google.github.io/webcodecs/mp4/index.html

I don't know if it will help you. I got a pretty clear "Unable to parse avcC" error message when it wasn't working.

**Comment by dhkimest** [comment]
Your demo was very helpful!
FrameData of my code needs to add NAL length.
It's positioned first of four bytes.

Thank you for your support!

**Comment by tguilbert-google** [comment]
I'm glad it helped! I'm assuming that your issue is resolved? If so, I am closing this issue, feel free to reopen if needed.
