### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by umaar** [WICG/web-codecs#101]
Hey I'm an outsider to this project, but was interested in learning more about it and possibly making a [side-project](https://github.com/umaar/video-everyday) of mine to use this. Long story short, that project is a web app which coordinates with a Node.js backend, which in turn calls various `ffmpeg` commands to trim and stitch various videos together.

Will this specification support such use cases in the browser? E.g. could I request a small portion of `http://localhost/video.mp4` from client-side JS, play it back in the browser, and allow it to be stitched to another `other-video.mp4`, and then create a `final-output.mp4` which can be uploaded over the network, or even downloaded?

The source videos would match this sort of codec:

![image](https://user-images.githubusercontent.com/381495/97642288-b14e7100-1a3c-11eb-8b58-e79540ac51cd.png)

Is any of that possible or have I completely misunderstood what this spec is about?  

And on that note, if it is possible, I wonder how the browser would cope with processing GB's worth of 4k video for example.

**Comment by sandersdan** [comment]
WebCodecs provides the core part of such a project, the decoders and encoders. You should be aware that browsers are not likely to ship with encoders as capable as your own FFmpeg build; for example Chrome might use OpenH264 where you are likely to prefer libx264.

WebCodecs also does not assist with demuxing or muxing, although I expect that JS solutions will become available over time.

**Comment by umaar** [comment]
Interesting and good to know. Thanks very much for explaining!
