### ISSUE TITLE
how to set codecString to decode H.264 frame ?

### ISSUE THREAD

**Issue by ahfuzhang** [WICG/web-codecs#102]
```
  const init = {
    output: handleFrame,
    error: (e) => {
      console.log(e.message);
    },
  };

  const config = {
    codec: "vp8",  //here
    codedWidth: cnv.width,
    codedHeight: cnv.height,
  };

  const decoder = new VideoDecoder(init);
  decoder.configure(config);
```

how to set codecString to decode H.264 ?
I already try those, and not works:
`
h264
h.264
avc1
avc1.42E01E
avc1.4D401E
avc1.64001E
mp4v
`

thanks!

**Comment by chcunningham** [comment]
The avc1.* style string is what you want. 

For example, here's a demo that uses "avc1.4d401e"
https://tguilbert-google.github.io/webcodecs/mp4/index.html

The details of '*' section will depend on your h264 profile and level. Can you say what profile and level your frame is? 

Also, if you can upload the sample code and h264 content somewhere we can take a closer look.

**Comment by chcunningham** [comment]
Assuming the issue is resolved. Please re-open if needed.
