### ISSUE TITLE
frame level navigation?

### ISSUE THREAD

**Issue by shi-yan** [WICG/web-codecs#105]
I'm very excited to see web-codecs.

but I don't seem to see a way to navigate to a specific frame, something similar to av_seek_frame. 

We wanted to build an AI labelling tool for video data using web technology. We gave up because there is no easy way to navigate to a frame. The existing api only allows navigation using a timestamp. But timestamp is not precise.

**Comment by chcunningham** [comment]
Glad you're excited! 

av_seek_frame is a higher level concept for moving around in the file. WebCodecs offers lower level decoder/encoder abstractions. To do something like seeking, you'll want to demux your file in javascript, grab the frame you're interested in, and feed that to WebCodecs.

Here's an example that uses mp4box.js to do the demuxing in JS
https://tguilbert-google.github.io/webcodecs/mp4/index.html

**Comment by shi-yan** [comment]
Thank you so much for the explanation.

**Comment by marklundin** [comment]
It seems that when you've deuxed a file into chunks you can't arbitrarily decode a chunk into a frame if it's out of sequence. You have to run through previous frames in sequence to reach the required frame before it can be decoded correctly. Is this expected behaviour? @shi-yan @chcunningham have you manged to test this out ?

**Comment by chcunningham** [comment]
Yes, that is expected. You will need to always start decoding with a "key frame" (some codecs may call it a random-access-point).  The non-key frames refer to prior key frames such that they are impossible to decode out of sequence. Your stream should have key frames periodically such that you can start with the nearest key frame that precedes the chunk you actually want, then feed all the intermediate chunks up to (and including) your desired chunk. On the output callback, you can just `close()` and ignore all the VideoFrames until you get one with the timestamp you desire. You may need to call `codec.flush()` to force it out of the pipeline if you don't want to decode any extra chunks beyond the desired frame.
