### ISSUE TITLE
Distinguish AVCC from AVC for H.264

### ISSUE THREAD

**Issue by HuaChunbo** [WICG/web-codecs#106]
AVC is Advanced Video Coding from ISO/IEC 14496-10, which basically equals to H.264 from ITU-T. Regarding the bitstream format, we should use avcC for AVCConfig which usually requires AVCDecoderConfigurationRecord from ISO/IEC 14496-15.

**Comment by chcunningham** [comment]
Thanks for filing. Is there a particular part of the spec where you'd like to see this addressed? At present I think we mention avcC only in a note about the VideoDecoderConfig.description. You might be interested in PRs #113 and #117 which touch on this.

**Comment by chcunningham** [comment]
No reply, so closing. Please re-open if needed.

**Comment by HuaChunbo** [comment]
Thanks. Here comes the suggestion of addressing spot, which is in section "3.2. AvcBitstreamFormat" of AVC (H.264) WebCodecs Registration spec:
enum AvcBitstreamFormat {
  "annexb",
  "avc",
};
It's clearer and better to use avcc instead of avc in order to distinguish AVCC from AVC for H.264.

**Comment by sandersdan** [comment]
An "avcC" is an "AVC Configuration", not a bitstream format.

"avc" OTOH is ambiguous. It could mean AVC, the codec, but in this case it means "AVC canonical stream format", the bitstream format from ISO/IEC 14496-15.

**Comment by chcunningham** [comment]
I agree with all posts above. IMHO, the "avc" seems like the lesser of two evils.

**Comment by HuaChunbo** [comment]
It seems that there is no place in the current AVC specs specifying bitstream types with specific individual terminologies...
What I proposed here is actually from conventional discussions about AVC codec within different groups when talking about bitstream. avcC is the configuration structure specific for no-start-code elementary stream, while annexb is the section name from the spec for byte stream format. Both are conventional names.

Actually, the only text I can find from https://www.itu.int/rec/T-REC-H.264 is 
"6.1 Bitstream formats
This clause specifies the relationship between the NAL unit stream and byte stream, either of which are referred to as the
bitstream.
**The bitstream can be in one of two formats: the NAL unit stream format or the byte stream format.** The NAL unit stream
format is conceptually the more "basic" type. It consists of a sequence of syntax structures called NAL units. This sequence
is ordered in decoding order. There are constraints imposed on the decoding order (and contents) of the NAL units in the
NAL unit stream.
The byte stream format can be constructed from the NAL unit stream format by ordering the NAL units in decoding order
and prefixing each NAL unit with a start code prefix and zero or more zero-valued bytes to form a stream of bytes. The
NAL unit stream format can be extracted from the byte stream format by searching for the location of the unique start code
prefix pattern within this stream of bytes. Methods of framing the NAL units in a manner other than use of the byte stream
format are outside the scope of this Recommendation | International Standard. The byte stream format is specified in
Annex B."

Maybe another option is "nalustream" vs "bytestream"? Sound not a good one...

**Comment by sandersdan** [comment]
The format indicated by "avc" in WebCodecs is **not** a NAL unit stream. It is also not defined in H.264, it is defined in ISO/IEC 14496-15, the binding between H.264 and MP4.
