### ISSUE TITLE
H.264 compatibility with webm output of MediaRecorder is a bit tortured, webm has no avcC

### ISSUE THREAD

**Issue by OllieJones** [WICG/web-codecs#125]
When MediaRecorder generates a webm datastream with the `video/x-matroska;codecs="avc1.42001E"` MIME type, it doesn't present any `avcC` atom (that's an MP4 atom, not a Matroska thing). 

It's possible to reconstruct the `avcC` atom from the webm bitstream: the SPS and PPS NALUs appear in the video bitstream before the first idr (intraframe) picture.  Code can fish them out and cons up the necessary data structure.  But it's a pain in the neck.

In webm, the PPS and SPS are repeated, in the bitstream, at the beginning of every Cluster, before every idr picture. 

It would be nice if there were symmetry between the MediaRecorder encoder and WebCodecs VideoDecoder in this respect. 

How about generalizing the VideoDecoder so it doesn't absolutely need the avcC if it finds the SPS and PPS

(I've discovered this in a project to use VideoDecoder in place of [Broadway ](https://github.com/OllieJones/Broadway)for decoding and rendering h.264. )

By the way, the bitstream in webm is in Annex B (0 0 0 1 startcodes before NALUs) format, rather than the packet format.

**Comment by chcunningham** [comment]
Hi @OllieJones. I'm happy to report that annex B decoder support is on the horizon. The rough plan is signal your preferred format by simply including/excluding the avcc via the VideoDecoderConfig.description. 

I envision having a codec "registry" in the spec that describes this behavior. I'll work on that this quarter.

**Comment by chcunningham** [comment]
Ah, I see you found our other older annex b bug #72 . I'll close this to de-dup, but please re-open if there's something here that needs distinct tracking.

**Comment by OllieJones** [comment]
See https://gist.github.com/OllieJones/6845734fe572b91cf907f8ef87c67541 for the hack to make the avcC atom from the MediaRecorder key frame NALU sequence.
