### ISSUE TITLE
h264 encoding & decoding - get avcC description?

### ISSUE THREAD

**Issue by asineth0** [WICG/web-codecs#133]
I have a MediaStreamTrack that I'm reading with VideoTrackReader into a VideoEncoder and I'm trying to encode it to H264/AVC and then decode it back to a canvas.

Here's how I'm seting up the VideoEncoder & VideoDecoder.

```js
const config = {
  codec: "avc1.42001e",
  width: settings.width,
  height: settings.height,
  framerate: settings.frameRate,
  bitrate: 10_000_000,
};
```

It errors though, and says "H.264 configuration must include an avcC description" so I'm wondering if I'm able to retrieve that from the VideoEncoder somewhere or if I have to provide that myself. 

If I have to provide it myself, how would I do that? (maybe not the best place to ask, but I'm clueless)

**Comment by chcunningham** [comment]
The encoder output callback should now have a second parameter which provides the VideoDecoderConfig needed to decode the newly encoded stream. This emitted config will have the description set to provide the avcc.

The published spec doesn't mention this yet, but the change is a work in progress (preview here). 

The Chromium implementation already behaves this way with the caveat that it emits the decoder config with every output, as opposed to just when the config changes. We'll get that fixed.

**Comment by asineth0** [comment]
I ended up figuring it out, on the VideoEncoder's output function it outputs the extradata.
