### ISSUE TITLE
Failed to execute 'decode' on 'AudioDecoder': Cannot call 'decode' on a closed codec.

### ISSUE THREAD

**Issue by tinchoz49** [WICG/web-codecs#137]
Hi, 

I was experimenting with the AudioDecoder and since the AudioEncoder is not ready yet I thought to use https://github.com/chris-rudmin/opus-recorder to encode an AudioNode into opus chunks.

When I try to decode the chunks using the AudioDecoder I got:

Failed to execute 'decode' on 'AudioDecoder': Cannot call 'decode' on a closed codec.

What it means that error? I thought that `opus` is open but maybe the problem is how `opus-recorder` is encoding the chunk. 

demo: https://codepen.io/tinchoz49/pen/GRNjgNV

Anyway I thought to ask here, maybe I'm missing something. 

Thank you.

**Comment by tguilbert-google** [comment]
By the way, if your're interested in getting AudioFrames directly, the latest canary build have the MediaStreamTrackProcessor, which allows you to get AudioFrames from an audio MediaStreamTrack ([see demo](https://storage.googleapis.com/dalecurtis/audio-breakout-box.html))

**Comment by tguilbert-google** [comment]
One more thing :P The Opus audio encoder is supported as of 89.0.4389.0 in Chromium, but we're looking into [a bug ](https://crbug.com/1175377) with it.

**Comment by tinchoz49** [comment]
Thank you for the quick response @tguilbert-google 

> By the way, if you're interested in getting AudioFrames directly, the latest canary build has the MediaStreamTrackProcessor, which allows you to get AudioFrames from an audio MediaStreamTrack (see demo)

this is awesome
