### ISSUE TITLE
I would like to know whether the encoded data can carry the configuration information of its decoder. If so, can you give me an example?

### ISSUE THREAD

**Issue by TTiamo** [WICG/web-codecs#154]

**Comment by chcunningham** [comment]
I'm not sure what's being asked. Are you trying to construct the decoder or configure it? 

Here's a demo that does both:
https://tguilbert-google.github.io/webcodecs/mp4/index.html

Relevant code snippets:

```
  async function onFrame(frame) {
     // Do something with frame...
  }

  let decoder = new VideoDecoder({
    output: onFrame,
    error: e => console.error(e),
  });

decoder.configure(config);
// config = {codec: "avc1.4d401e", codedHeight: 360, codedWidth: 640, description: Uint8Array(39)}
  ```

**Comment by chcunningham** [comment]
It is possible (perhaps even likely) that the encoded data (e.g. the AV1 bitstream) may describe enough of the stream properties such that you could derive a VideoDecoderConfig that could be used to configure the VideoDecoder. Is this what you're aiming to do?

How much can be derived and exactly how to do so would be specific to the codec. Can you say what codec you're trying to use?

This is not generally how we expect folks to fill out the config though. Ideally, the config info would be somehow stored outside of the bitstream (e.g. in the track metadata of a webm file).

**Comment by chcunningham** [comment]
Please re-open if you have followup questions.
