### ISSUE TITLE
Changing settings in frame chunks vs. separate chunks

### ISSUE THREAD

**Issue by steveanton** [WICG/web-codecs#20]
As of #14 the mechanism for changing encoder settings is to bundle a dictionary with the input frame. An alternative discussed was to have a separate chunk type that only has changed settings (no input frame).

**Comment by steveanton** [comment]
Pros/cons I could come up with:

### Bundling setting changes with inputs:
Pros:
- Obvious how it works with backpressure.

Cons:
- Prevents settings from being changed early which could impact performance if the setting change requires some time.

### Separate setting change chunks:
Pros:
- Allows settings to be changed early without new input.

Cons:
- Backpressure on setting change chunks doesn't really make sense.

**Comment by pthatcherg** [comment]
I think this is should be addressed in the bigger issue at https://github.com/WICG/web-codecs/issues/35

**Comment by steveanton** [comment]
I think these are two different issues. #20 here refers to dynamic settings which I believe do not have any objections to being in band. #35 refers to static settings which require a re-initialization. I would not be surprised if we support dynamic vs. static setting changes differently.
