### ISSUE TITLE
Use the same codec names as MediaCapabilities

### ISSUE THREAD

**Issue by pthatcherg** [WICG/web-codecs#31]
MediaCapabilities uses a content type of "video/foo; codecs=A.B.C".  We should probably use the "A.B.C" instead of what we have currently.  For example, instead of "h264", use "avc1.4200" or instead of "vp9", "vp09.00.10.08".  It's a little crazy and I can't find any RFCs for these things, but here is where Chromium parses them: 

https://cs.chromium.org/chromium/src/media/base/mime_util_internal.cc?g=0&l=820

**Comment by chcunningham** [comment]
Woot!

avc and mp4a are here https://tools.ietf.org/html/rfc6381
vp9 is here https://www.webmproject.org/vp9/mp4/
av1 is here https://aomediacodec.github.io/av1-isobmff/#codecsparam

The dolby stuff is probably in some dolby doc.

**Comment by chcunningham** [comment]
Old bug. The spec now works as described.
