### ISSUE TITLE
Is it possible to do our codec or media processing based on WASM

### ISSUE THREAD

**Issue by fideltian** [WICG/web-codecs#32]
Hello.
     we have a requirement that we need do ourselves encode/decoder/packetization ourselves on WASM. And then transport the data via webtransport or RtcQuic. In the begining, we might need do some media process, besides the encoder/decoder. 

 What we need is :
    1) read the raw data of captured media data, such as YUV video data, or PCM audio data,etc. Then the raw data could be passed to wasm/js module.
    2) It will be better the capture could be worked on worker.
    3) The data passing is efficient without memory copy.
    4) hardware accelerate encoder/decoder could be used by wasm/ js module, which is a Plus.

Could this spec satisfy our requirement?

**Comment by guest271314** [comment]
> 1) read the raw data of captured media data, such as YUV video data, or PCM audio data,etc. Then the raw data could be passed to wasm/js module.

It is not clear why it is expected that the "raw data" of a video is "YUV" (see https://stackoverflow.com/a/39048445; https://github.com/brion/yuv-canvas). 


The audio data can be expressed as an `AudioBuffer` using [`decodeAudioData()`](https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata)

> 3. If can _decode_ is _true_, attempt to decode the encoded [audioData](https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata-audiodata-successcallback-errorcallback-audiodata) into [linear PCM](https://webaudio.github.io/web-audio-api/#linear-pcm). In case of failure, set _can decode_ to _false_.

or a `Float32Array` using `AudioWorkletNode`, see https://github.com/web-platform-tests/wpt/blob/d5be80a86d4f938250c075ac12414ad47516969c/webaudio/js/worklet-recorder.js (see https://github.com/WebAudio/web-audio-api/issues/2011 relevant to `options` at the code).

> 2) It will be better the capture could be worked on worker.

What does "capture" mean in this context? 

> 3) The data passing is efficient without memory copy.

The term "efficient" is not clearly defined. "efficient" compared to precisely what approaches that are not "efficient"? 

> 4) hardware accelerate encoder/decoder could be used by wasm/ js module, which is a Plus.

Not sure what that means. Encoding and decoding _any_ unknown audio and/or video codec by "wasm/js"?

**Comment by fideltian** [comment]
https://stackoverflow.com/a/39048445; https://github.com/brion/yuv-canvas).
> 
> The audio data can be expressed as an `AudioBuffer` using [`decodeAudioData()`](https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata)
> 
> > 1. If can _decode_ is _true_, attempt to decode the encoded [audioData](https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata-audiodata-successcallback-errorcallback-audiodata) into [linear PCM](https://webaudio.github.io/web-audio-api/#linear-pcm). In case of failure, set _can decode_ to _false_.
> 
> or a `Float32Array` using `AudioWorkletNode`, see https://github.com/web-platform-tests/wpt/blob/d5be80a86d4f938250c075ac12414ad47516969c/webaudio/js/worklet-recorder.js (see [WebAudio/web-audio-api#2011](https://github.com/WebAudio/web-audio-api/issues/2011) relevant to `options` at the code).
> 
> > 1. It will be better the capture could be worked on worker.
> 
> What does "capture" mean in this context?
> 
> > 1. The data passing is efficient without memory copy.
> 
> The term "efficient" is not clearly defined. "efficient" compared to precisely what approaches that are not "efficient"?
> 
> > 1. hardware accelerate encoder/decoder could be used by wasm/ js module, which is a Plus.
> 
> Not sure what that means. Encoding and decoding _any_ unknown audio and/or video codec by "wasm/js"?



> > 1. read the raw data of captured media data, such as YUV video data, or PCM audio data,etc. Then the raw data could be passed to wasm/js module.
> 
> It is not clear why it is expected that the "raw data" of a video is "YUV" (see https://stackoverflow.com/a/39048445; https://github.com/brion/yuv-canvas).
> 
> The audio data can be expressed as an `AudioBuffer` using [`decodeAudioData()`](https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata)
> 
> > 1. If can _decode_ is _true_, attempt to decode the encoded [audioData](https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata-audiodata-successcallback-errorcallback-audiodata) into [linear PCM](https://webaudio.github.io/web-audio-api/#linear-pcm). In case of failure, set _can decode_ to _false_.
> 
> or a `Float32Array` using `AudioWorkletNode`, see https://github.com/web-platform-tests/wpt/blob/d5be80a86d4f938250c075ac12414ad47516969c/webaudio/js/worklet-recorder.js (see [WebAudio/web-audio-api#2011](https://github.com/WebAudio/web-audio-api/issues/2011) relevant to `options` at the code).
> 
> > 1. It will be better the capture could be worked on worker.
> 
> What does "capture" mean in this context?
> 
> > 1. The data passing is efficient without memory copy.
> 
> The term "efficient" is not clearly defined. "efficient" compared to precisely what approaches that are not "efficient"?
> 
> > 1. hardware accelerate encoder/decoder could be used by wasm/ js module, which is a Plus.
> 
> Not sure what that means. Encoding and decoding _any_ unknown audio and/or video codec by "wasm/js"?

**Comment by fideltian** [comment]
I did the wrong action of closing the issue.

1) we need to do the vidoe processing ourselved based on WASM. So we might need the RGBA or YUV data of video from WEBRTC capture. We could get the raw data of audio through webaudio API.

2) Capture here means "WebRTC Capture audio/video". It means we would like to get the raw data from worker scope.

4)  some CPU has some hardware accelerating encoder/decoder. It will be better to expose the capability to applicaiton layer.

**Comment by guest271314** [comment]
You can currently use `ImageCapture.grabFrame()` to get `ImageBitmap` instances of the captured video frames then process the frames. That procedure is possible right now, without waiting for WebCodecs to specify anything.

**Comment by fideltian** [comment]
The API returns ImageBitmap , which is not the raw data. It must be drawed to canvas and then get the imageData from Canvas API.

**Comment by murillo128** [comment]
You can read the image data via the `VideoTrackReader.readable` and implement your encoder as a `TransformStream`

**Comment by chcunningham** [comment]
Old bug! Fidel and Chrome folks have discussed this directly, but for other folks reading along:

> What we need is :
> 1) read the raw data of captured media data, such as YUV video data, or PCM audio data,etc. Then the raw data could be passed to wasm/js module.

Yes, originally offered via VideoTrackReader / AudioTrackReader, but this is now deprecated in favor of (as of #131) using [MediaStreamTrackProcessor](https://w3c.github.io/mediacapture-insertable-streams/#mediastreamtrackprocessor). Demo [here](https://webrtc.github.io/samples/src/content/insertable-streams/video-processing/).

2) It will be better the capture could be worked on worker.

Using MediaStreamTrackProcessor, you will have the option to transfer the `readable` stream to a worker. 

3) The data passing is efficient without memory copy.

Working with WASM unfortunately imposes some copies, as described in https://github.com/WICG/reducing-memory-copies/issues/1

4) hardware accelerate encoder/decoder could be used by wasm/ js module, which is a Plus.

At least in Chrome, we will prefer acceleration by default where available. PR #118 will add the ability to strictly require that hardware acceleration be used (which will fail to create the codec when acceleration is not available). 

Please re-open if more to discuss.
