### ISSUE TITLE
Support VideoFrame creation from yuv data

### ISSUE THREAD

**Issue by murillo128** [WICG/web-codecs#45]
Currently there is no way of creating a VideoFrame from an existing image data, so the only way to implement a custom media stream track is to paint it on a canvas object and capture the stream from it.

This would allow implementing custom decoders in WASM and half the work required for the funy hat use case.

**Comment by chcunningham** [comment]
The spec now offers two mechanisms to construct from ImageData
https://wicg.github.io/web-codecs/#videoframe-constructors

Re: WASM, there are still some unfortunate copies required. Tracked here:
https://github.com/WICG/reducing-memory-copies/issues/1

Feel free to re-open if more to discuss.
