### ISSUE TITLE
Error Recovery

### ISSUE THREAD

**Issue by sandersdan** [WICG/web-codecs#49]
After an error in processing (configure, decode, or otherwise), there are multiple potential ways we could allow recovery:

- Automatically recover at the next keyframe.
- Recover after the next configure().
- Recover after the next reset().
- The above, but discard (abort) all queued requests first.
- Do not allow recovery at all.

The latter two are easier to reason about, but some apps would be simpler with a different choice. Perhaps it should be configurable.

(Example that is difficult to reason about: if a configure() fails or is aborted, what configuration would we use to decode the next keyframe? This may be a reason to require configure() after reset()--it is always unambiguous.)

**Comment by chcunningham** [comment]
> Do not allow recovery at all.

This is what we landed on, as it is simplest both conceptually and from an interface POV.
