### ISSUE TITLE
Interleaved / Non-Interleaved Decoded Audio

### ISSUE THREAD

**Issue by AnthumChris** [WICG/web-codecs#59]
After audio is decoded, would it be best for the decoder to return 1 buffer of interleaved audio or multiple buffers of decoded audio per channel (e.g. 2 buffers for stereo audio)?

Would de-interleave functionality be natively provided by the platform/UA or would it be the developer's responsibility?  I think the former could be an easier API for devs to use.

**Comment by padenot** [comment]
The web platform only use planar buffers for audio, but that's probably because there was no interaction with codecs or IO, where interleaved audio is often preferred.

A interleaving/deinterleaving routine is probably very very fast in wasm, but I don't know how fast.

**Comment by chcunningham** [comment]
Currently the proposal is to use the same AudioBuffer from Web Audio, containing planar float 32. See 
https://wicg.github.io/web-codecs/#ref-for-dom-audioframe-buffer

> A interleaving/deinterleaving routine is probably very very fast in wasm, but I don't know how fast.
I agree, and @AnthumChris seemed to accept. I'll go ahead and close this issue, but please re-open if needed.
