### ISSUE TITLE
Add Audio/VideoTrackWriter to Explainer

### ISSUE THREAD

**Issue by sandersdan** [WICG/web-codecs#61]
It should be possible to mux encoded content using VideoTrackWriter with MediaRecoder (encoded frames &rarr; VideoTrackWriter &rarr; VideoTrack &rarr; MediaRecorder &rarr; muxed content). We would need to verify that this combination is capable of correctly representing reordered frames (or reject them at runtime).

The same API could be used to handle encoding as well (raw frames &rarr; VideoTrackWriter &rarr; VideoTrack &rarr; MediaRecorder &rarr; muxed content). It's unclear if this is useful to WebCodecs users.

**Comment by chcunningham** [comment]
@dalecurtis investigated and concluded MR API would need invasive changes to do anything more than basic muxing (e.g. fragmented MP4).

**Comment by chcunningham** [comment]
Plans for Audio/VideoTrackWriter are now deprecated in favor of using https://w3c.github.io/mediacapture-insertable-streams/#track-generator
