### ISSUE TITLE
Remove profile field in VideoEncoderInit for encoder configure, and use rfc6381 codec-id instead of codec for all audio and video codec configuration

### ISSUE THREAD

**Issue by daijh** [WICG/web-codecs#66]
A few reasons:

- The codec-id defined in rfc6381, provides codec, profile, level and other details of codec. It is widely used in MediaStream Recording and HTMLMediaElement. It is unified method to pass codec parameters.

https://tools.ietf.org/html/rfc6381

- Codec-id already contains profile. Don't need another profile field.
	avc1.42E01 - H.264 Constrained baseline profile
	vp09.02.10.08 - VP9 profile 2
	av01.1.04M.08 - AV1 profile high

- Codec-id provides more parameters to control encoder, maybe bit depth and color space, easy to extend in the future.

- Align with VideoDecoder configure, VideoDecoder dose not provide profile. 
   And it is able to unify all codecs configuration (audio, video, decoder, encoder) in WebCodecs.

<pre><code>
// Decoder does not provide profile
dictionary EncodedVideoConfig {
  required DOMString codec;
  BufferSource description;
  double sampleAspect;
};

// Remove profile to align with decoder
dictionary VideoEncoderInit {
  required DOMString codec;
  DOMString profile;
  required VideoEncoderTuneOptions tuneOptions;
  required VideoEncoderOutputCallback output;
  WebCodecsErrorCallback error;
};
</code></pre>

**Comment by sandersdan** [comment]
We (Chrome implementors) had a discussion about this when we last reviewed the encode API, and we concluded that codec strings are not ideal for this case. In particular, we were not sure that apps always know what H.264 level they want, nor do we want them to have to discover the exact set of profiles and levels supported by the browser.

I'm not even really sure that we know the levels supported by MediaCodec on Android. In general I expect encoders to pick a relatively high level and then use a target bitrate well below the level limit.

In any case decode and encode should be using the same data structure for this information.

**Comment by chcunningham** [comment]
We since flip flopped on this and started using the the string style from rfc6381. All the above points (positives and negatives) are valid. For now we've decided to use the strings mostly for consistency with other web media APIs.
