### ISSUE TITLE
Require hardware acceleration

### ISSUE THREAD

**Issue by chcunningham** [WICG/web-codecs#75]
something like 

```decoder.configure({ codec: 'vp8', acceleration: 'require' })```

which should fail to configure if hw acceleration is not available for the given configuration. Same thing encoder. 

This allows apps who bring their own software codecs in WASM to prefer those when we would otherwise be using software internally. 

We have [a version of this enum](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/webcodecs/video_encoder_config.idl;drc=e9b426c19ec3dfc778eea5da7e040f90f8260377;l=9) already in Chromium for the encoder. We should make it a more generically named thing to share w/ decode and formally spec it.

**Comment by yisibl** [comment]
Looking back through [history](https://chromium-review.googlesource.com/c/chromium/src/+/2704733/13/third_party/blink/renderer/modules/webcodecs/video_decoder.cc#340), I think this has already been renamed to `hardwareAcceleration`?https://github.com/w3c/webcodecs/issues/239#issuecomment-888451816
