### ISSUE TITLE
How to try it out

### ISSUE THREAD

**Issue by AlexVestin** [WICG/web-codecs#77]
Hello,

Is it possible to try the webcodecs implementation, and if so how? Skimming through the readme/explainer/wicg link I couldn't find any info on if it is available to test out, though [chromestatus](https://www.chromestatus.com/feature/5669293909868544) says it is available on chrome 86 behind a flag, but I couldn't find the flag.

**Comment by tguilbert-google** [comment]
You can turn it on via chrome://flags/#enable-experimental-web-platform-features.

Passing the "--enable-blink-features=WebCodecs" via the command line should also work.

**Comment by AlexVestin** [comment]
@tguilbert-google Thank you! Really excited about this project
