### ISSUE TITLE
Seek to target video frame number using webcodecs

### ISSUE THREAD

**Issue by lincolnneu** [WICG/web-codecs#87]
Does webcodecs support seeking to a specific frame number? Given a url to a video e.g. mp4, say I want to seek to frame number 16, can the video decoder return me the image data of frame 16?

**Comment by tguilbert-google** [comment]
WebCodecs is lower level than the HTML5 Video Element, and doesn't have the concept of seeking. Instead, it just outputs frames for the chunks it is given.

If you want the 16th frame, you need to give a VideoDecoder the chunks necessary to decode the 16th frame.

**Comment by lincolnneu** [comment]
Looking forward to seeing someone publishes open source video player based on web-codecs and support frame accurate seeking!

**Comment by lincolnneu** [comment]
Maybe we can use mp4box.js to generate chunk of target frame and feed to VideoDecoder.

**Comment by chcunningham** [comment]
You could definitely use MP4 box or similar js library to extract the encoded chunks and build a custom player on top of WebCodecs. 

Looks like the main question is resolved. Please re-open if needed.

**Comment by marklundin** [comment]
If I grab all the chunks from mp4box, I can decode them as long as I do so in sequence. However I can't decode a specific chunk out of order. I guess this make sense as they depend on previous chunks, but what would be the process of decoding a single frame at a given time. Would it be something like the following?

1. demux all chunks
2. Find the first chunk with type 'key' before the required time T
3. decode this chunk followed by all subsequent chunks untill time T is reached

Thanks for your help!

**Comment by sandersdan** [comment]
This is a large topic so I won't go into all the details, but what you describe will cover 95% of cases. It's not usually necessary to demux all of the chunks, you should be able to use just the initialization segment and the target chunk.

I believe that chcunningham was however suggesting https://github.com/gpac/mp4box.js which has a `seek()` method. I would expect all JS demuxer implementations to have something similar.

**Comment by ldenoue** [comment]
@marklundin I implemented your idea. A tricky bit is determining how often we might get key frames, because we want to start sending the chunks to the VideoDecoder at a key chunk. So I used a `GOP` constant that computes the timestamp in microseconds that corresponds to 1024 GOP frames at 60 fps.
What do you think would be a better idea?

```
let frameOffset = null;
let seeked = false;
const GOP = 1024 * 1000 * 1000 / 60 // assume we will find a key frame at least every 1024 frames at 60 FPS

let demuxer = new MP4Demuxer(url, {
    onConfig(config) {
      setStatus("decode", `${config.codec} @ ${config.codedWidth}x${config.codedHeight}`);
      config.codec = codec
      decoder.configure(config);
    },
    onChunk(chunk) {
      if (!frameOffset) {
        frameOffset = chunk.timestamp
      }
      if (!seeked && chunk.type === 'key' && chunk.timestamp - frameOffset >= videoStart - GOP) {
        seeked = true;
        console.log('seeked');
      }
      if (seeked)
        decoder.decode(chunk);
    },
    onFinish() {
      console.log('decoder onFinish')
    },
    setStatus
  });
```

**Comment by Rodeoclash** [comment]
I feel like we're edging closer to having all the technical requirements in place to produce a low level media player for the web that can operate precisely on frames.

Some interesting work going on around porting libav to the web here: https://github.com/Yahweasel/libav.js (theirs also a sister project available which can bridge libav to WebCodecs).

I'm currently experimenting in this area at the moment and would be keen to hear from anyone else that's also working in this space.
