### ISSUE TITLE
Failed to execute 'configure' on 'VideoEncoder': required member framerate is undefined.

### ISSUE THREAD

**Issue by ytakio** [WICG/web-codecs#89]
In Chrome 86.0.4240.75, it seems that `VideoEncoder` must be set with a `framerate` via configure method.
I'm not sure whether it is just missing in spec or bug of implementation.

But I think it may not be good spec that Encoder must be cofigured with a fixed `framerate`.
It looks like that VFR(variable frame rate) use cases like frame dropped rendering and randomly captured frame are not taken into account if `VideoEncoder` must be set with fixed `framerate`.

How about it adopts a flag of fixed frame rate like bellow?

```js
dictionary VideoEncoderConfig {
  required DOMString codec;
  unsigned long long bitrate;
  boolean fixedFramerate;
  required unsigned long width;
  required unsigned long height;
};
```

**Comment by sandersdan** [comment]
There is no mention of framerate in the draft spec, I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1139059 for the issue in Chromium.

I'll leave this open to discuss this aspect of the configuration. I don't think Chrome's implementation is using it as a fixed frame rate, rather it is being used for bitrate control to compute the target bits-per-frame.

**Comment by ytakio** [comment]
Thank you for your filing issue in chromium.
I understood that `framerate` is for rate control. `max framerate` may be appropriate rather.

**Comment by ytakio** [comment]
I've confirmed that this issue has been already fixed at Chrome88.
Thanks!
