### ISSUE TITLE
Spec promise<bool> IsConfigSupported() 

### ISSUE THREAD

**Issue by chcunningham** [WICG/web-codecs#98]
This tracks spec work to offer a static asynchronous API to check whether a given configuration is supported. 

Calling configure() with a _valid_ but _unsupported_ configuration will trigger a fatal error (see #53) via the error callback. Validity can be assessed synchronously and throw an exception. Support is harder because it may require async checks (e.g. if a given codec is only available via hardware acceleration, such acceleration typically happens in a separate process and may require IPC to verify details of support). 

Our first thought was to have configure() return a promise, but this has a few drawbacks:
1) the only other async->promise API is currently flush(), and its promise indicates that the flush has been completed. having configure() return a promise to indicate that its configuration is supported (but not necessarily applied) is inconsistent and hard to reason about. 
2) If we attempt to address 1 by only resolving once the configuration is supported _and applied_, realtime users may suffer visible side-effects of needing to react to a preventable failure at the last minute

So instead we offer this static async API which users should call prior to calling configure().

**Comment by sandersdan** [comment]
Removing the promise from configure() was a huge improvement to complexity and removed a lot of edge cases for the Chrome implementation. Specifically:

- If we return a promise, it's only useful (compared to an error callback) if apps wait for it to resolve before enqueuing chunks.
- This increases latency compared to other fallback strategies (unless we discard chunks queued after the configuration, which is likely to explode the state machine in the implementation and in apps).
- This prevents us from deferring configuration changes. In some cases we don't have a signal better than 'we tried to decode a chunk and it succeeded/failed', so we want to be able to defer configuration until we have a chunk.

I vote that isConfigSupported() should be best-effort indication.

**Comment by chcunningham** [comment]
> I vote that isConfigSupported() should be best-effort indication.

+1. I'll update the PR accordingly.
